--Таблица Направление
INSERT INTO DIRECTION VALUES
(01, N'renaissance'),
(02, N'early renaissance'),
(03, N'abstractionism'),
(04, N'avant-garde'),
(05, N'academicism'),
(06, N'actionism'),
(07, N'Alla prima'),
(08, N'empire'),
(09, N'animalism'),
(10, N'application'),
(11, N'anachronism'),
(12, N'underground'),
(13, N'arte Povera'),
(14, N'art Nouveau'),
(15, N'art Deco'),
(16, N'aerography'),
(17, N'baroque'),
(18, N'biedermeier'),
(19, N'battle genre'),
(20, N'household genre'),
(21, N'vanitas'),
(22, N'veduta'),
(23, N'verism'),
(24, N'geometric abstract art'),
(25, N'hyperrealism'),
(26, N'urban landscape'),
(27, N'gothic'),
(28, N'graphics'),
(29, N'grisaille'),
(30, N'dadaism'),
(31, N'decorative painting'),
(32, N'divisionism'),
(33, N'impressionism'),
(34, N'caravaggism'),
(35, N'kitsch'),
(36, N'classicism'),
(37, N'cloisonnism'),
(38, N'constructivism'),
(39, N'cosmism'),
(40, N'cubism'),
(41, N'cubofuturism'),
(42, N'lowbrow art'),
(43, N'rayism'),
(44, N'mannerism'),
(45, N'metarealism'),
(46, N'miserabilism'),
(47, N'minimalism'),
(48, N'modern'),
(49, N'modernism'),
(50, N'still life'),
(51, N'naive'),
(52, N'naturalism'),
(53, N'neoclassicism'),
(54, N'neoplasticism'),
(55, N'neorealism'),
(56, N'neo-expressionism'),
(57, N'nude'),
(58, N'Op Art'),
(59, N'orphism'),
(60, N'parsuna'),
(61, N'pastoral'),
(62, N'primitivism'),
(63, N'pop Art'),
(64, N'post-impressionism'),
(65, N'postmodernism'),
(66, N'pre-Raphaelitism'),
(67, N'proto-Renaissance'),
(68, N'pointillism'),
(69, N'purism'),
(70, N'realism'),
(71, N'rococo'),
(72, N'romanticism'),
(73, N'ippian genre'),
(74, N'historical genre'),
(75, N'capriccio'),
(76, N'marina'),
(77, N'sentimentalism'),
(78, N'symbolism'),
(79, N'street art'),
(80, N'surrealism'),
(81, N'suprematism');